# This dictionary maps easy to remember names to Youtube video IDs
# after adding an ID here, you can use the {{youtube <shortname>}}
# syntax in your markdown files to embed the video into the page!
videos = Dict(
              "course-intro" => "Hs5abYdC7EQ",
              "installation" => "Hs5abYdC7EQ",
              "feynman"  => "EYPapE-3FRw",
              "cute-one"     => "Hs5abYdC7EQ",
              "images-intro" => "Hs5abYdC7EQ",
              "convolution"  => "Hs5abYdC7EQ",
              "ted-talk"     => "Hs5abYdC7EQ",
              "image-seam"   => "Hs5abYdC7EQ",
              "array-views"  => "Hs5abYdC7EQ",
              "image-seam-reminiscing" => "Hs5abYdC7EQ",
              "james-image-seam" => "Hs5abYdC7EQ",
              "conv-gpus"    => "Hs5abYdC7EQ",
              "conv-real-world" => "Hs5abYdC7EQ",
              "types"        => "Hs5abYdC7EQ",
              "dispatch"     => "Hs5abYdC7EQ",
              "ides"         => "Hs5abYdC7EQ",
              "structure"    => "Hs5abYdC7EQ",
              "macros-intro" => "Hs5abYdC7EQ",
              "understanding-data" => "Hs5abYdC7EQ",
              "introspection" => "Hs5abYdC7EQ",
              "covid-data" => "Hs5abYdC7EQ",
              "dataframes" => "Hs5abYdC7EQ",
              "functions-are-objects" => "Hs5abYdC7EQ",
              "covid-live" => "Hs5abYdC7EQ",
              "computational-illustrated" => "Hs5abYdC7EQ",
              "matrix-graphs" => "Hs5abYdC7EQ",
              "verbs-nouns" => "Hs5abYdC7EQ",
              "grant-epidemic" => "Hs5abYdC7EQ",
              "r0"           => "Hs5abYdC7EQ",
              "self-doc"     => "Hs5abYdC7EQ",
              "paramtypes"   => "Hs5abYdC7EQ",
              "raytracing1"  => "Hs5abYdC7EQ",
              "byop"         => "Hs5abYdC7EQ",
              "what-is-array" => "Hs5abYdC7EQ",
              "raytracing2" => "Hs5abYdC7EQ",
              "resistors"   => "Hs5abYdC7EQ",
              "hier-thinking" => "Hs5abYdC7EQ",
              "pde-schemes" => "Hs5abYdC7EQ",
              "multigrid" => "Hs5abYdC7EQ",
)
